# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install swag and Build Documentation
      run: go install github.com/swaggo/swag/cmd/swag@latest && swag init

    - name: Build
      run: go build -ldflags "-s -w" -o ./go-aliyunmc .

    - name: Test
      run: go test -v $(go list ./... | grep -v /docs)

    - name: Combine
      run: mkdir output && cp *.tmpl.sh go-aliyunmc config.example.toml README.md output

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v6.0.0
      with:
        # Artifact name
        name: go-aliyunmc
        # A file, directory or wildcard pattern that describes what to upload
        path: ./output/*
        # The desired behavior if no files are found using the provided path. Available Options:
        if-no-files-found: error
        # Duration after which artifact will expire in days. 0 means using default retention.
        retention-days: 30
        # The level of compression for Zlib to be applied to the artifact archive. The value can range from 0 to 9: - 0: No compression - 1: Best speed - 6: Default compression (same as GNU Gzip) - 9: Best compression Higher levels will result in better compression, but will take longer to complete. For large files that are not easily compressed, a value of 0 is recommended for significantly faster uploads.
        compression-level: 6
        # If true, an artifact with a matching name will be deleted before a new one is uploaded. If false, the action will fail if an artifact for the given name already exists. Does not fail if the artifact does not exist.
        overwrite: false
        # If true, hidden files will be included in the artifact. If false, hidden files will be excluded from the artifact.
        include-hidden-files: false
        
